name: Triggered by pull request
on:
  pull_request:
    branches:
      - main
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"